apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-deployment
  labels:
    app: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: vprocache01
        image: memcached
        ports:
          - name: cache-port
            containerPort: 11211