apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    podSpec:
      pod:
      - name: vproapp
        image: vprofile/vprofileapp:V1
        ports:
          - name: app-port
            containerPort: 8080
            